import '../models/product_model.dart';

final List<ProductModel> foodProducts = [
  ProductModel(
    name: "Fresh Apple",
    imageUrl: "assets/Categories/food1.jpg",
    description: "Your small act of kindness can make a big difference! 🌍💖 Donate today and help bring hope, change lives, and make the world a better place."
        " Every contribution matters—let's create a brighter future together! 🙌✨ #DonateNow",
    phoneNumber: "+92 3124835214",
    houseNumber: "House no:276",
    streetNumber: "Street no:2",
    impAreaLocation: "Ali Town",
    city: "Lahore",
    country: "Pakistan",
    uploadDate: "2 days ago",
  ),

  ProductModel(
    name: "Organic Banana",
    imageUrl: "assets/Categories/food2.jpg",
    description: "Your small act of kindness can make a big difference! 🌍💖 Donate today and help bring hope, change lives, and make the world a better place."
        " Every contribution matters—let's create a brighter future together! 🙌✨ #DonateNow",
    houseNumber: "House no:276",
    streetNumber: "Street no:2",
    impAreaLocation: "Ali Town",
    city: "Lahore",
    country: "Pakistan",
    phoneNumber: "+92 3124835214",
    uploadDate: "1 day ago",
  ),
  ProductModel(
    name: "Dairy Milk Chocolate",
    imageUrl: "assets/Categories/food3.jpg",
    description: "cjefliewfaenfaghliraeglaiergjl",
    houseNumber: "House no:276",
    streetNumber: "Street no:2",
    impAreaLocation: "Ali Town",
    city: "Lahore",
    country: "Pakistan",
    phoneNumber: "+92 3124835214",
    uploadDate: "5 hours ago",
  ),

  ProductModel(
    name: "Dairy Milk Chocolate",
    imageUrl: "assets/Categories/food4.jpg",
    description: "cjefliewfaenfaghliraeglaiergjl",
    houseNumber: "House no:276",
    streetNumber: "Street no:2",
    impAreaLocation: "Ali Town",
    city: "Lahore",
    country: "Pakistan",
    phoneNumber: "+92 3124835214",
    uploadDate: "5 hours ago",
  ),

  ProductModel(
    name: "Dairy Milk Chocolate",
    imageUrl: "assets/Categories/food5.jpg",
    description: "cjefliewfaenfaghliraeglaiergjl",
    houseNumber: "House no:276",
    streetNumber: "Street no:2",
    impAreaLocation: "Ali Town",
    city: "Lahore",
    country: "Pakistan",
    phoneNumber: "+92 3124835214",
    uploadDate: "5 hours ago",
  ),
];
List<ProductModel> furnitureProducts = [
  ProductModel(name: "Sofa",
      imageUrl: "assets/Categories/furniture1.jpg",
      description: "cjefliewfaenfaghliraeglaiergjl",
      houseNumber: "House no:276",
      streetNumber: "Street no:2",
      impAreaLocation: "Ali Town",
      city: "Lahore",
      country: "Pakistan",
      phoneNumber: "+92 3124835214",
      uploadDate: "5 hours ago"),

  ProductModel(name: "Sofa", imageUrl: "assets/Categories/furniture2.jpg",
      description: "cjefliewfaenfaghliraeglaiergjl",
      houseNumber: "House no:276",
      streetNumber: "Street no:2",
      impAreaLocation: "Ali Town",
      city: "Lahore",
      country: "Pakistan",
      phoneNumber: "+92 3124835214",uploadDate: "5 hours ago"),
  ProductModel(name: "Sofa", imageUrl: "assets/Categories/furniture3.jpg",
      description: "Your small act of kindness can make a big difference! 🌍💖 Donate today and help bring hope, change lives, and make the world a better place."
          " Every contribution matters—let's create a brighter future together! 🙌✨ #DonateNow",
      houseNumber: "House no:276",
      streetNumber: "Street no:2",
      impAreaLocation: "Ali Town",
      city: "Lahore",
      country: "Pakistan",
      phoneNumber: "+92 3124835214",
      uploadDate: "5 hours ago"),
];

List<ProductModel> bloodProducts = [
  ProductModel(name: "Blood A+", imageUrl: "assets/Categories/bloodDon1.jpg",
      description: "Be a hero—save a life! ❤️🩸 Your blood donation can make the difference between life and death for someone in need. Just a few minutes of your time can give someone a second chance at life. Donate blood today and be the reason"
          " someone smiles tomorrow! 🙌 #DonateBlood #SaveLives",
      houseNumber: "House no:276",
      streetNumber: "Street no:2",
      impAreaLocation: "Ali Town",
      city: "Lahore",
      country: "Pakistan",
      phoneNumber: "+92 3124835214",
      uploadDate: "5 hours ago"),
  ProductModel(name: "Blood A+", imageUrl: "assets/Categories/bloodDon2.jpg",
      description: "Be a hero—save a life! ❤️🩸 Your blood donation can make the difference between life and death for someone in need. Just a few minutes of your time can give someone a second chance at life."
          " Donate blood today and be the reason someone smiles tomorrow! 🙌 #DonateBlood #SaveLives",
      houseNumber: "House no:276",
      streetNumber: "Street no:2",
      impAreaLocation: "Ali Town",
      city: "Lahore",
      country: "Pakistan",
      phoneNumber: "+92 3124835214",
      uploadDate: "5 hours ago"),
  ProductModel(name: "Blood A+", imageUrl: "assets/Categories/bloodDon3.jpg",
      description: "Be a hero—save a life! ❤️🩸 Your blood donation can make the difference between life and death for someone in need. Just a few minutes of your time can give someone a second chance at life."
          " Donate blood today and be the reason someone smiles tomorrow! 🙌 #DonateBlood #SaveLives",
      houseNumber: "House no:276",
      streetNumber: "Street no:2",
      impAreaLocation: "Ali Town",
      city: "Lahore",
      country: "Pakistan",
      phoneNumber: "+92 3124835214",
      uploadDate: "5 hours ago"),
];

List<ProductModel> medicineProducts = [
  ProductModel(name: "Paracetamol", imageUrl: "assets/Categories/medicines1.jpg",
      description: "cjefliewfaenfaghliraeglaiergjl",
      houseNumber: "House no:276",
      streetNumber: "Street no:2",
      impAreaLocation: "Ali Town",
      city: "Lahore",
      country: "Pakistan",
      phoneNumber: "+92 3124835214",
      uploadDate: "5 hours ago"),
  ProductModel(name: "Paracetamol", imageUrl: "assets/Categories/medicines2.jpg",
      description: "cjefliewfaenfaghliraeglaiergjl",
      houseNumber: "House no:276",
      streetNumber: "Street no:2",
      impAreaLocation: "Ali Town",
      city: "Lahore",
      country: "Pakistan",
      phoneNumber: "+92 3124835214",
      uploadDate: "5 hours ago"),
];